[package]
name = "kataster"
version = "0.1.0"
authors = ["Boris Boutillier <boris.boutillier@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.3.*"
rand = "0.7.3"
#bevy_rapier2d = { git = "https://github.com/Bobox214/bevy_rapier" , branch="rapier_configuration"}
#bevy_rapier2d = { path = "/home/boris/work/rust/forks/bevy_rapier/bevy_rapier2d" }
bevy_rapier2d = "0.5.*"

