[package]
name = "meshmaker"
version = "0.1.0"
authors = ["dcz <gihuac.dcz@porcupinefactory.org>"]
license = "AGPL-3.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
immense = "0.1.*"
rand = "0.7.*"
